name: my projects
favicon: null
layout_spectrum: 0.65565
typography_spectrum: 0.26502
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#08080a'
    - '#6a6a6c'
    - '#eaece7'
    - '#bfbebc'
    - '#b14528'
  brandStrength: 0.5
  lightness: 0.9133479737211019
  saturation: 0.5800764129962772
  rhythmicContrast: 0.5
purpose: []
