favicon: null
name: projects
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5800764129962772
  brandStrength: 0
  lightness: 0.9133479737211019
  brandColors:
    - '#000000'
    - '#01FF01'
    - '#0101FF'
    - '#FF0101'
    - '#FBFC03'
  rhythmicContrast: 0.7434120818506926
typography_spectrum: 0.40086
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
